zoom_factor: 2               # Default upsampling factor for segmenting cells
match_method: "1"           # Matching strategy: 
                            # "1" - For each child frame, choose the most similar annotated frame as its parent (recommended)
                            # "2" - Use the same annotated frame as parent for all child frames
                            # "3" - Match against all annotated frames; keep consensus matches and unique orphan matches

folder_path: dataset/ZM9624_github/   # Path to load the dataset
save_folder: dataset/ZM9624_github/   # Path to save outputs (usually same as folder_path)

threshold: 0.5               # Linking probability threshold for positive match
sim_threshold: null          # Use null (None) by default during training
weights_path: null           # Use null (None) by default during training

train_val: train             # Use "train" to require ground truth in annotation.h5 (coordinates and worldline_id)

centroid_ref: null           # Use null (None) to disable centroid masking
extension_length: null       # Use null (None) to disable mask extension

ratio: 0.1                   # Class balancing weight for linking probability; valid values: 0.1–1.0
nearby_search_num: 5         # Number of nearest neighbors considered as edges

model_path: ZM9624_github/model/  # Path to save or load model weights
code_dir: Matching_anchor         # Path to the Matching_anchor code directory
